# Configuration file for http://goreleaser.com

builds:
  - main: ./cmd/server/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X github.com/dailymotion/jx-pipelines-visualizer/cmd/server.version={{.Version}}
      - -X github.com/dailymotion/jx-pipelines-visualizer/cmd/server.commit={{.Commit}}
      - -X github.com/dailymotion/jx-pipelines-visualizer/cmd/server.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - format: binary

dockers:
  - dockerfile: Dockerfile.goreleaser
    extra_files:
      - web/static/
      - web/templates/
    image_templates:
      - "ghcr.io/dailymotion/{{.ProjectName}}:{{ .Version }}"
      - "ghcr.io/dailymotion/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/dailymotion/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/dailymotion/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/dailymotion/{{.ProjectName}}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

before:
  hooks:
    # package Helm chart
    - rm -rf .cr-release-packages
    - mkdir -p .cr-release-packages
    - helm package --app-version={{if .IsSnapshot}}latest{{else}}{{.Version}}{{end}} --version={{if .IsSnapshot}}0.0.0{{else}}{{.Version}}{{end}} --destination .cr-release-packages charts/jx-pipelines-visualizer

changelog:
  sort: asc
